### ISSUE TITLE
对贵项目贡献条目公正性的质疑

### ISSUE THREAD

**Issue by gouku** [dd-center/vdb#11584]
前段时间，就是否添加明前奶绿词条已经有了非常多的讨论：https://github.com/dd-center/vdb/pull/10278

各位审核人员质疑的点无非是：

> @Radekyspec 或者你得让我们拿到「这个人之后会做/有计划做V」的证据

根据其最新动态，已经有了相应的live2d披露： https://t.bilibili.com/705368182898032672

![00ceb13ad64a40e88ac026e034ed572d09f43c5f](https://user-images.githubusercontent.com/9361308/190339060-b9f884d0-5890-400b-ba69-1bdee59b00c9.gif)

如果说之前[相关企划的信息](https://github.com/dd-center/vdb/pull/10278#issuecomment-1195794138)不足以作为证据，那这次的live2d立绘足以说明「这个人之后会做/有计划做V」了吧？

EOE这种大企划发一张图就可以秒收录，底边小v就要刨开肚子看看有几碗粉才可以？甚至拖了四个月至今没有收录。

最让我无法理解的还不是这个，而是当我看到了最近的一个commit：https://github.com/dd-center/vdb/commit/975d355ea0e6561d9d654d381d648ef82bd4f7a2

<img width="358" alt="image" src="https://user-images.githubusercontent.com/9361308/190340372-eb60b2ef-e244-4390-a278-4ff2472ad2cf.png">

请问各位审核人员，其中说的「两位新v」，哪里有做v的迹象？

https://space.bilibili.com/10077845

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/9361308/190340805-cfca0bc3-329d-41e8-a4b2-afa3db23c1dc.png">

https://www.acfun.cn/u/67917455

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/9361308/190340939-89593add-0ed5-4235-8bc5-25159502ddb8.png">

https://space.bilibili.com/87386257

<img width="1339" alt="image" src="https://user-images.githubusercontent.com/9361308/190341078-eed003bd-98dc-4be5-b5fb-4ce1e117c4cc.png">

梅露蒂雅Melodia这位，我看了他/她所有的动态，没有找到任何「这个人之后会做/有计划做V」的证据，请问 @Radekyspec，为什么这个PR就可以通过呢？就因为头像是个二次元图？

![screencapture-space-bilibili-87386257-dynamic-2022-09-15-03_44_13](https://user-images.githubusercontent.com/9361308/190345738-9d6fc49b-fe66-4dd1-ac1c-48e448c59a94.png)

https://vtbs.moe/ 这个项目我想流量应该也不小了吧，vdb本身也有[诸多贡献者](https://github.com/dd-center/vdb#contributors-)，既然仓库都放到了独立的org下，那作为一个公共开源的项目而非个人项目，项目的管理者和审核人员应该尽量保证项目的公正性，而不应该带有过多的主观情绪。

**Comment by simon300000** [comment]
您好

我个人没有直接参与这个 commit 的审核。Melodia 审核通过可能是因为她在虚拟区直播，以及确实有皮：https://www.bilibili.com/video/BV1vU4y1v7nG

而Aeka0确实在加入前就已经被删除了：
https://github.com/dd-center/vdb/pull/11552
https://github.com/dd-center/vdb/commit/825f559daf32946ee0d80e10d4294c9f06d79d8e


但是 vdb 规则相对不完善是确实的，我也希望可以改善这个方面。如果你愿意的话，欢迎加入审核组/对规则提出建议，真的很抱歉

**Comment by wudifeixue** [comment]
我前面看了圈，对你这句话我也很认同
提merge主要的一个原因是，现在其实不少第三方都在依赖你们这个数据库，会去抓一些动态、统计之类的内容。等出道了再加vdb**那就会错过前期的一些数据了**
我好心痛啊，我也好心疼这些数据啊！
不过其实。。vtbs.moe有个私货名单，那边也有悄悄[统计数据的](https://github.com/dd-center/vtbs.moe/blob/1e44e6fbaacdcc1af18d8ba6c342a1d849365068/api/interface/vdb.ts#L56)例如一些官号...https://vtbs.moe/detail/32472953 就是这个不太多人知道，也不太方便加这些，还要commit，就偷懒了没加这位...
不过就像Simon也有提一样，我其实也很欢迎你过来，平时大部分审核活都@Radekyspec 包了，我做的蛮少的，所以我也会非常尊重他的意见，毕竟大伙都是用无私奉献的项目。

哦对，另外我挺同意现在把这位给merge了，那我就直接merge咯？

**Comment by ilharp** [comment]
vdb 是一个公共开源的项目而非个人项目，如果你对 vdb 感兴趣或者想要帮助改进的话，可以加入 vdb 的审核团队，与我们一同建设 vdb~

**Comment by Chen-Luan** [comment]
作为一名贡献者我想先提醒您，遇到问题应该友好地提出您的见解，否则这将对解决问题没有任何帮助。

基于友好交流的原则，我将向您解释一些疑问，如有疏漏敬请谅解。

---

首先是收录标准的讨论issue，请您自行参阅#113与#6503，如有疑问请在issue下comment

基于现行收录标准并考虑服务器负荷等情况，vdb审核成员（至少我本人是）基于“有皮、经常用皮才收录”的标准来进行审核的。因此您提交的此pr并不在收录范围内。

其次，对于不合规的成员，我们也会定期审核并清除，例如最近处理的#11488 #11490 #11492 #11493 #11496 #11497 #11499 #11502

再三，VDB目前已经处理了超过5000条的pr，一部分pr确实难以定量评估是否达到收录标准，因此这一部分不可避免的存在一些主观因素，还请您谅解。
