### ISSUE TITLE
收录规则是不是太过宽泛了

### ISSUE THREAD

**Issue by PoiDaisuki** [dd-center/vdb#117]
像用户
113956408
416397670
3406546
等似乎完全不符合vtb的定义（甚至包括空账号？）

另外已毕业VTB是不是可以考虑打个已毕业一类的tag然后把数据定在毕业前...看着不少毕业vtb掉粉被唐突捅了一刀emmm

**Comment by simon300000** [comment]
其中有说是要出道的，看起来没出道，我去制裁他（
不过3406546是本组的另一个程序man @KinoriN ，在测试软件时加入的，会处理的www

**Comment by PoiDaisuki** [comment]
所以已毕业Vtuber有什么打算吗（

**Comment by PoiDaisuki** [comment]
不对这玩意儿怎么回复emmm←连git都用不来的咸鱼

**Comment by simon300000** [comment]
我是会收到提醒的啦
毕业的vtb我准备怎么样操作一下，但是我有点忙儿（

**Comment by Afanyiyu** [comment]
还是觉得应该在数据中加上一个'status'值来描述主播是否活动，以此来区分主播状态。而非移除不符合规则的主播。毕竟这是一个数据爬取而非用于界定的项目（  https://github.com/dd-center/vdb/issues/113#issuecomment-562139062  ）。毕竟界定条件（尤其是对于尚未首播或暂停活动的主播）个人有个人的想法，vdb中规定一个boolean的界定条件还是不如status中提供一个enum值符合规范。
总而言之，对simon的压榨仍需继续。
#113
