### ISSUE TITLE
VTB补

### ISSUE THREAD

**Issue by 3316472807** [dd-center/vdb#1173]
## 请求添加以下VTB

1. https://space.bilibili.com/159995981

2.没有正式出道但是已经在活动啦

3.

4.

## 检查单

- [x] 我已确认我请求添加的用户符合VTB标准
- [x] 我已确认我请求添加的用户尚未录入vdb
- [x] 我已确认我请求添加的用户没有与任何处于open状态的Issue或PR重复

**Comment by shugen002** [comment]
https://t.bilibili.com/387564066243573964?tab=2 尴尬
