### ISSUE TITLE
审核流程提议：先过后审

### ISSUE THREAD

**Issue by Chen-Luan** [dd-center/vdb#12091]
**在tag系统实装之前的替代方案**
对于活跃、有近期出道或直播计划，但尚不满足收录标准的vtb，先予以收录，同时创建一个撤回的pr，若15天内不达标则撤回
先过后审的原pr与撤回pr均添加“先过后审”label

**Comment by shugen002** [comment]
我觉得可以，但对于未出道的需要有明确的出道计划时间，如果仅停留在possible的，如老物转生但迟迟没有明确时间的不建议采用该方案。

**Comment by shugen002** [comment]
也不是说那部分人的数据没价值，只是感觉那些老物转生在那里卡半天对于那些已经出道的人有点emmmm~
