### ISSUE TITLE
VTB撤销

### ISSUE THREAD

**Issue by 8MiYile** [dd-center/vdb#138]
https://space.bilibili.com/21882176/

**Comment by PoiDaisuki** [comment]
这个看起来没有问题啊？（但是似乎没有在监控列表上？）

**Comment by 8MiYile** [comment]
> 这个看起来没有问题啊？（但是似乎没有在监控列表上？）

我意思是请在主页上撤销此VUP,感谢

**Comment by PoiDaisuki** [comment]
额...为什么要撤销呢？

**Comment by 8MiYile** [comment]
,之前一开始听说有这个网站我和那边的房管说好不要让这位VUP显示到贵站的主页上

**Comment by PoiDaisuki** [comment]
刚刚去翻了一下...这位根本就不在监控范围里......（所有收录都要人工进行的所以= =只要不来提交基本上就不会被记录上）

**Comment by 8MiYile** [comment]
那有人提交这位VUP的话,请直接拒绝,感谢

**Comment by PoiDaisuki** [comment]
这个的话就交给simon了x

**Comment by 8MiYile** [comment]
好的那提前感谢了

**Comment by simon300000** [comment]
等等回去弄个测试黑名单。
这个需求挺怪的，不小心可能就收录了→_→
