### ISSUE TITLE
123heheheabc 不要直接改json改出问题

### ISSUE THREAD

**Issue by simon300000** [dd-center/vdb#1478]
噔噔咚？

https://github.com/dd-center/vdb/commit/9f09f9069225d566c8af50629dcf4d6005788dbf#commitcomment-39333139

**Comment by simon300000** [comment]
https://github.com/dd-center/vdb/commit/1f071b0357e2c5e478617dd554db2299ec4a47f0

**Comment by simon300000** [comment]
https://github.com/dd-center/vdb/commit/5e70599a01358ba603dbccf0ea6c11af8265d7e0

**Comment by shugen002** [comment]
我也是直接改json的，不过json的格式我是记住了。。。

**Comment by 123heheheabc** [comment]
啊这，有些信息发生了变更，好吧后面就不用json修改信息了，我就单独新建一个吧😥😥😥！

**Comment by 123heheheabc** [comment]
或者说一下json的格式

**Comment by shugen002** [comment]
@123heheheabc 未来6小时请暂时不要操作，github似乎不是很稳定，具体看https://www.githubstatus.com/

**Comment by 123heheheabc** [comment]
![Screenshot_2020-05-31-22-58-07-16](https://user-images.githubusercontent.com/59812388/83355500-5ad6ec80-a34f-11ea-9e9c-183e5c756d91.png)
![Screenshot_2020-05-31-22-55-23-33](https://user-images.githubusercontent.com/59812388/83355503-5dd1dd00-a34f-11ea-9e49-d8ea146e12ab.png)
@simon300000 
又出问题了吗？

**Comment by simon300000** [comment]
我去修好了

Simon
simon30002021@icloud.com

**Comment by 123heheheabc** [comment]
@simon300000 这些显示错误#1468#1472#1497#1499#1501#1517#1519

**Comment by 123heheheabc** [comment]
@simon300000 这些显示错误#1468 #1472 #1497 #1499 #1501 #1517 #1519

**Comment by Afanyiyu** [comment]
不建议直接改动JSON文件。

**Comment by Afanyiyu** [comment]
另外不建议对所有 PR 进行 Approve，请务必在详细查看并比对要求之后再进行操作。
2 Approves 即可合并 PR，所以请认真对待 Approve。
时间较久的不少 PR 是有待商讨的，已标注 Changes Requested。

**Comment by Afanyiyu** [comment]
此外，也不建议在 PR 版 at 其他人（甚至不建议 Request Reviewer
