### ISSUE TITLE
VTB补

### ISSUE THREAD

**Issue by 1823442674** [dd-center/vdb#1587]
## 请求添加以下VTB

1.人生LING_Channel
 https://space.bilibili.com/29002992

2.

3.

4.

## 检查单

- [x] 我已确认我请求添加的用户符合VTB标准
- [x] 我已确认我请求添加的用户尚未录入vdb
- [x] 我已确认我请求添加的用户没有与任何处于open状态的Issue或PR重复

**Comment by 1823442674** [comment]
人生LING_Channel
https://space.bilibili.com/29002992

**Comment by 123heheheabc** [comment]
@1823442674 
update #1542
信息在审核
不要刷屏
