### ISSUE TITLE
这两个号也收录到了项目中的初衷是什么

### ISSUE THREAD

**Issue by zhz1237ok** [dd-center/vdb#193]
![image](https://user-images.githubusercontent.com/38283893/76972077-11d6e500-6969-11ea-967a-1e709f1c73a4.png)
![image](https://user-images.githubusercontent.com/38283893/76972096-18655c80-6969-11ea-80b6-c8dee0bdfff0.png)
https://space.bilibili.com/420711844/
https://space.bilibili.com/4307809/
因为这两个号已经有了V的官号
收录这两个号的话
是不是意味着如果未来有更多在 已有官号的前提下 的 同V海盗组 的号也要进行收录呢

**Comment by KinoriN** [comment]
![image](https://user-images.githubusercontent.com/45453624/77028675-72e7d280-69d4-11ea-8bb4-7258c5e2719a.png)

**Comment by zhz1237ok** [comment]
只要发了V的熟肉就能收录到fan类型吗，是基于什么初衷和准则的

**Comment by KinoriN** [comment]
初衷就是尽可能多的收集数据
