### ISSUE TITLE
Change requested from submit.vtbs.moe

### ISSUE THREAD

**Issue by STDongKl** [dd-center/vdb#2005]
7月出道目前正在筹备当中，个人直播势，暂且无任何人设（或许是她不想说）；暂时情况是出道先在YOUTUBE,T台；后在B站，B站元老级粉丝正在聚集中。

### description

add: セツナ_Official.json
> <https://space.bilibili.com/12103144>

```
-----BEGIN SUBMIT BLOCK-----bmFtZTpVMVJFYjI1blMydz0KcHV0OjQ0Szc0NE9FNDRPS1gwOW1abWxqYVdGc0xtcHpiMjQ9OmV3b2dJQ0p1WVcxbElqb2dld29nSUNBZ0ltcHdJam9nSXVPQ3UrT0RoT09EaWw5UFptWnBZMmxoYkNJS0lDQjlMQW9nSUNKaFkyTnZkVzUwY3lJNklIc0tJQ0FnSUNKaWFXeHBZbWxzYVNJNklDSXhNakV3TXpFME5DSUtJQ0I5Q24wPQ==-----END SUBMIT BLOCK-----
```

Submit from <https://submit.vtbs.moe>, please evaluate the automatic Pull Request

**Comment by STDongKl** [comment]
7月出道目前正在筹备当中（皮7月出生，个人视频在做中，周边亚克力牌已经订好初版了），个人直播势，她本人表示人设她自己喜欢就随便改；暂时情况是出道先在YOUTUBE,T台；后在B站，B站元老级粉丝正在聚集中。（B站视频她之前删光了）

**Comment by NyaMisty** [comment]
可以的话补一下youtube、twitter账号，我们再merge
