### ISSUE TITLE
Dream Horizon社团一期生重整

### ISSUE THREAD

**Issue by 8MiYile** [dd-center/vdb#211]
Dream Horizon 社团 除保留官方号 其他社员移除出社团列表内并添加以下虚拟主播
https://space.bilibili.com/488744718
https://space.bilibili.com/480460413
https://space.bilibili.com/5887731
https://space.bilibili.com/8161250
https://space.bilibili.com/418158697
感谢

**Comment by 123heheheabc** [comment]
其他的所属成员都要被移除？

**Comment by 8MiYile** [comment]
> 其他的所属成员都要被移除？

是的

**Comment by simon300000** [comment]
现在已经修复了吧？
如果还没有请reopen
