### ISSUE TITLE
VTB补

### ISSUE THREAD

**Issue by ATKghost** [dd-center/vdb#214]
紫海由爱Official
https://space.bilibili.com/525105971

黑桐亚里亚Official
https://space.bilibili.com/4911722

**Comment by shugen002** [comment]
duplicated #208 #209 
add in https://github.com/dd-center/vdb/commit/78bffb9a041a276b1a47cadb1b6f4843c9ef554c https://github.com/dd-center/vdb/commit/f36c677c04b1b9325a7c848e65261b32fcd832ce
