### ISSUE TITLE
VTB补

### ISSUE THREAD

**Issue by MTOL0430** [dd-center/vdb#217]
建议首先参考 [这里](https://github.com/dd-center/vdb/issues/113#issuecomment-560273409) 来确定要添加的用户确实符合 VTB 标准

这里写上个人空间连接就行了
https://space.bilibili.com/429075

**Comment by shugen002** [comment]
https://github.com/dd-center/vdb/blob/3a45b8b57ce79864d4ff8c5044b776dd5883f70e/vtbs/%E5%85%83OL.json
