### ISSUE TITLE
VTB补

### ISSUE THREAD

**Issue by zhihaofans** [dd-center/vdb#223]
建议首先参考 [这里](https://github.com/dd-center/vdb/issues/113#issuecomment-560273409) 来确定要添加的用户确实符合 VTB 标准

VirtuaReal Project新成员（未发布自我介绍视频）

https://space.bilibili.com/370687588

https://space.bilibili.com/370687372

https://space.bilibili.com/370688671

https://space.bilibili.com/370689210

https://space.bilibili.com/370689338

**Comment by shugen002** [comment]
现在都有了
