### ISSUE TITLE
VTB补

### ISSUE THREAD

**Issue by starskim** [dd-center/vdb#227]
建议首先参考 [这里](https://github.com/dd-center/vdb/issues/113#issuecomment-560273409) 来确定要添加的用户确实符合 VTB 标准

这里写上个人空间连接就行了
https://space.bilibili.com/136037914

**Comment by shugen002** [comment]
https://github.com/dd-center/vdb/blob/ce6b7de5c4b6c50f9e5ed36937fdb3abf1e02bc6/vtbs/%E7%B3%96%E5%95%BEChannel.json
