### ISSUE TITLE
VTB补（你服务器submit.vtbs.moe炸了！！）

### ISSUE THREAD

**Issue by Janet-Baker** [dd-center/vdb#2782]
## 请求添加以下VTB

1. 早见咲
Hayami Saki
早見咲Saki
https://space.bilibili.com/541696090

## 检查单

- [!] 我已确认我请求添加的用户符合VTB标准
- [!] 我已确认我请求添加的用户尚未录入vdb
- [!] 我已确认我请求添加的用户没有与任何处于open状态的Issue或PR重复

**Comment by simon300000** [comment]
谢谢，但是为什么炸了呢？就是是打不开网页还是什么情况呀

**Comment by Janet-Baker** [comment]
服务器连接拒绝。挂代理也不行。

**Comment by Janet-Baker** [comment]
还有，这个“早見咲”什么时候提交的？？？我搜了issues和pr居然没搜到……还是看到报错之后搜UID搜到的

**Comment by simon300000** [comment]
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/12656264/91664013-9d45cc00-eaec-11ea-9b56-552c1d40c2ba.png">
可能之前就写进去了吧，这里搜索就能看到了（不过你打不开了。。。）

服务器连接拒绝，这可能是DNS的问题吗，有没有试过换DNS？


https://github.com/dd-center/vdb/issues/1983
这里是加进去的那个pr

**Comment by Janet-Baker** [comment]
这名字不对啊，怪不得搜不到
```
{
  "name": {
    "cn": "早见咲",
    "jp": "早見咲",
    "en": "Hayami Saki"
  },
  "accounts": {
    "bilibili": "541696090"
  }
} 
```
还是希望删掉重加。另外，实在搜不到twitter/youtube，这个人貌似也是住在B站的……

**Comment by Janet-Baker** [comment]
发现了一个神奇的事情
```
PS C:\Users\10632> nslookup submit.vtbs.moe
服务器:  XiaoQiang
Address:  192.168.31.1

非权威应答:
名称:    dd-center.github.io
Address:  127.0.0.1
Aliases:  submit.vtbs.moe

PS C:\Users\10632> ipconfig /flushdns

Windows IP 配置

已成功刷新 DNS 解析缓存。
PS C:\Users\10632> nslookup submit.vtbs.moe
服务器:  XiaoQiang
Address:  192.168.31.1

非权威应答:
名称:    dd-center.github.io
Address:  127.0.0.1
Aliases:  submit.vtbs.moe
```
怎么做到的？？？？？？
乖乖用手机提交吧……
