### ISSUE TITLE
123heheabc 来试试这个

### ISSUE THREAD

**Issue by simon300000** [dd-center/vdb#280]
@123heheheabc
来请试试这个
https://submit.vtbs.moe/

**Comment by 123heheheabc** [comment]
嗯好的

**Comment by 123heheheabc** [comment]
@simon300000 
![Screenshot_2020-04-17-21-28-06-91](https://user-images.githubusercontent.com/59812388/79574249-71ecb280-80f2-11ea-8542-03e0e85410ce.png)
这个就可以了吗？

**Comment by simon300000** [comment]
@123heheheabc 不用提交那么多次，一次可以提交很多东西的，这样审核也简单许多→_→

**Comment by simon300000** [comment]
@123heheheabc 我邀请你做为reviewer检阅人，可以来同意一下
https://github.com/dd-center/vdb/invitations
