### ISSUE TITLE
Wiki更新

### ISSUE THREAD

**Issue by Chen-Luan** [dd-center/vdb#6851]
写了一篇Wiki，希望对将来新招的审核君有帮助！
[审核君从入门到精通！](https://github.com/dd-center/vdb/wiki/%E5%AE%A1%E6%A0%B8%E5%90%9B%E4%BB%8E%E5%85%A5%E9%97%A8%E5%88%B0%E7%B2%BE%E9%80%9A%EF%BC%81)

**Comment by simon300000** [comment]
我立即进行一个bilibili的搬运
