### ISSUE TITLE
意外的报错

### ISSUE THREAD

**Issue by daBOSSer** [dd-center/vdb#8020]
在修改数据时出现了完全无关的报错 @simon300000 
https://github.com/dd-center/vdb/pull/8017
https://github.com/dd-center/vdb/runs/4080768146?check_suite_focus=true

![QQ截图20211102215737](https://user-images.githubusercontent.com/62653664/139861605-a02797fe-c6b2-456b-b74c-bfbf733abb6d.png)
![QQ截图20211102215716](https://user-images.githubusercontent.com/62653664/139861622-9daba69c-8642-4dcd-84dd-614880cddae3.png)

**Comment by daBOSSer** [comment]
此问题于已多次发生

**Comment by daBOSSer** [comment]
修好了，虽然不知道经历了什么

**Comment by simon300000** [comment]
这个报错在好几个commit之前就出现了，不过修好了就好（
