### ISSUE TITLE
似乎我关注的主播的数据很久没更新过了= =

### ISSUE THREAD

**Issue by fancySunset** [dd-center/vdb#8207]
https://vtbs.moe/detail/2049968320
像是粉丝数已经停留在这个数据很久了

**Comment by daBOSSer** [comment]
看上去不是一个up的问题==

**Comment by daBOSSer** [comment]
> https://vtbs.moe/detail/2049968320 像是粉丝数已经停留在这个数据很久了

问题已解决w
