### ISSUE TITLE
审核申请

### ISSUE THREAD

**Issue by Radekyspec** [dd-center/vdb#8906]
先贴一个账号保命（：https://space.bilibili.com/178856569
从20年底开始接触V，各种社团和个人势，大V小V都有了解接触过
目前每天可以拿出大约4小时来审核（实在是太闲了），如果能有幸当上的话
我会认真对待每一个Issue的awa

**Comment by simon300000** [comment]
欢迎🥰
https://github.com/dd-center/vdb/invitations

用不了那么久的其实 很快的

**Comment by shugen002** [comment]
破站私信你群号了，加一下。

**Comment by Chen-Luan** [comment]
> 破站私信你群号了，加一下。

有群号吗？我好像还没加，刚刚在B站看到，打算回来接着干
https://space.bilibili.com/1458800289
