### ISSUE TITLE
[功能建议] 新增国籍区分: 国V, 外V

### ISSUE THREAD

**Issue by eric2788** [dd-center/vdb#9100]
可能在每个 vtuber object 内新增一个 property 来区分
例如
```
locale: 'en' | 'jp' | 'cn'
```
或者
```
foreign: true | false
```

我曾经打算使用 v.name.default 用来区分日V 国V，结果发现并不准确，例如
美波七海 的 v.name.default 是 cn 而不是 jp

**Comment by simon300000** [comment]
🤔

**Comment by shugen002** [comment]
不点名某人，国籍反复横跳的怎么办？

**Comment by eric2788** [comment]
> 不点名某人，国籍反复横跳的怎么办？按自称的还是中之人被挖出来的？

就跟bls那種外語和國語就行，真反復橫跳可以直接加一個不穩定的狀態數值來表示（草）
