### ISSUE TITLE
关于UID1465794112的异常情况

### ISSUE THREAD

**Issue by Tinhone** [dd-center/vdb#9929]
该账号的json于4月27日添加，但直至issue发布前，该账号的vtbs主页仍无法正常打开，且在关于界面的logs发现关于该账号有多次RETRY以及SKIP RETRY
在4月30日添加的UID1462391335的vtbs主页却可以正常打开
这是什么情况...有点懵(＠_＠)

**Comment by wudifeixue** [comment]
刚刚修复了b站api，现在已经正常
https://github.com/dd-center/vtbs.moe/issues/357
